// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppConfig = { color_schema: string, contrast: number, mode: string, resize_filter: string, fallback_color: string, };

export type ConfigToml = { app: AppConfig, templates: { [key in string]: TemplateConfig }, };

export type TemplateConfig = { input_path: string, output_path: string | null, pre_hook: string, post_hook: string, };
