// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getServiceStatus: () => typedError<string, AppManagerError>(__TAURI_INVOKE("get_service_status")),
	isInitApp: () => typedError<boolean, null>(__TAURI_INVOKE("is_init_app")),
	initApp: (invokeConfig: ConfigToml) => typedError<null, AppManagerError>(__TAURI_INVOKE("init_app", { invokeConfig })),
	startService: () => typedError<null, AppManagerError>(__TAURI_INVOKE("start_service")),
	cleanService: () => typedError<null, AppManagerError>(__TAURI_INVOKE("clean_service")),
};

/* Types */
export type AppConfig = {
	color_schema: string,
	contrast: number,
	mode: string,
	resize_filter: string,
	fallback_color: string,
};

export type AppManagerError = { type: "Io"; message: string } | { type: "CommandFailed"; message: string } | { type: "ResourceNotFound"; message: string } | { type: "Serialization"; message: string } | { type: "Env"; message: string };

export type ConfigToml = {
	app: AppConfig,
	templates: { [key in string]: TemplateConfig },
};

export type TemplateConfig = {
	input_path: string,
	output_path: string | null,
	pre_hook: string,
	post_hook: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

