// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getServiceStatus: () => typedError<string, AppManagerError>(__TAURI_INVOKE("get_service_status")),
	isInitApp: () => typedError<boolean, null>(__TAURI_INVOKE("is_init_app")),
	initApp: () => typedError<AppVersions, AppManagerError>(__TAURI_INVOKE("init_app")),
	startService: () => typedError<null, AppManagerError>(__TAURI_INVOKE("start_service")),
	stopService: () => typedError<null, AppManagerError>(__TAURI_INVOKE("stop_service")),
	restartService: () => typedError<null, AppManagerError>(__TAURI_INVOKE("restart_service")),
	cleanApp: () => typedError<null, AppManagerError>(__TAURI_INVOKE("clean_app")),
	saveNewConfig: (invokeConfig: ConfigTomlDto) => typedError<null, AppManagerError>(__TAURI_INVOKE("save_new_config", { invokeConfig })),
	getConfig: () => typedError<ConfigTomlDto, AppManagerError>(__TAURI_INVOKE("get_config")),
	checkUpdates: () => typedError<AllUpdates, AppManagerError>(__TAURI_INVOKE("check_updates")),
	installDaemon: (url: string) => typedError<null, AppManagerError>(__TAURI_INVOKE("install_daemon", { url })),
	installMatugen: (url: string) => typedError<null, AppManagerError>(__TAURI_INVOKE("install_matugen", { url })),
};

/* Types */
export type AllUpdates = {
	daemon: UpdateMetadata,
	matugen: UpdateMetadata,
};

export type AppConfig = {
	color_schema: string,
	contrast: number,
	mode: string,
	resize_filter: string,
	fallback_color: string,
	prefer: string,
};

export type AppManagerError = { type: "Io"; message: string } | { type: "CommandFailed"; message: string } | { type: "ResourceNotFound"; message: string } | { type: "Serialization"; message: string } | { type: "Deserialization"; message: string } | { type: "Env"; message: string } | { type: "Network"; message: string } | { type: "DuplicateTemplateKey"; message: string };

export type AppVersions = {
	daemon: string,
	matugen: string,
};

export type ConfigTomlDto = {
	app: AppConfig,
	templates: TemplateItemDto[],
};

export type TemplateItemDto = {
	key: string,
	input_path: string,
	output_path: string | null,
	pre_hook: string,
	post_hook: string,
};

export type UpdateMetadata = {
	version: string,
	url: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

