name: Release Daemon

on:
  push:
    tags:
      - "daemon-v*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libglib2.0-dev pkg-config

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Daemon
        run: scripts/setup-daemon.sh

      - name: Create Release Draft
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: "${{ github.ref_name }}"
          draft: true
          files: dist/daemon
